"""Remove title constraint

Revision ID: 554288e7d376
Revises: a2d7c6ab4c25
Create Date: 2022-07-23 23:52:06.894293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554288e7d376'
down_revision = 'a2d7c6ab4c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Posts_title_key', 'Posts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Posts_title_key', 'Posts', ['title'])
    # ### end Alembic commands ###
